### ISSUE TITLE
eglot--lsp-position-to-point: Symbol’s function definition is void: eglot-move-to-column

### ISSUE THREAD

**Issue by jgarte** [nemethf/eglot-x#6]
Hi,

I get the following error:

```
[eglot] Connected! Server `ccls' now managing `(c-mode c-ts-mode c++-mode c++-ts-mode)' buffers in project `c_sandbox'.
eglot--lsp-position-to-point: Symbol’s function definition is void: eglot-move-to-column
error in process filter: eglot--lsp-position-to-point: Symbol’s function definition is void: eglot-move-to-column
```

It looks like it is related to this:

https://github.com/nemethf/eglot-x/blob/7d1724adf444bb0ddcf0c191c61365b1903031f0/eglot-x.el#L608

I am running the following version of Emacs:

`GNU Emacs 29.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.37, cairo version 1.16.0)`

WDYT

**Comment by nemethf** [comment]
Hi, thanks for the report.  `eglot-move-to-column` has been removed from the recent eglot.el.  As a workaround, I think, you can set `eglot-x-enable-encoding-negotiation` to nil.  As the documentation says: "The extension allows the client and the server to negotiate a proper encoding to be used in transmitting column positions.  It predates the standardized positionEncodings capability."  But Eglot now supports the standardized encoding negotiation, so the non-standard implementation in eglot-x does not really useful anymore.  I didn't remove it because clangd didn't support the standardized version the last time I checked.

**Comment by jgarte** [comment]
Thanks for the advice.

>  I didn't remove it because clangd didn't support the standardized version the last time I checked.

How did you check that? By reading the code for clangd or something else?

**Comment by nemethf** [comment]
> How did you check that? By reading the code for clangd or something else?

Searching the source code of clangd for the word `positionEncoding`.
